import Foundation

/// A source caption track from YouTube. The URL may be short-lived and stays in memory only.
nonisolated struct VideoCaptionTrack: Identifiable, Sendable, Hashable {
    let id: String
    let languageCode: String
    let languageName: String
    let url: URL
    let isAutoGenerated: Bool

    var displayName: String {
        guard isAutoGenerated else { return languageName }
        // YouTube often includes this qualifier in the source track name already.
        if languageName.range(of: "auto-generated", options: .caseInsensitive) != nil
            || languageName.range(of: "auto generated", options: .caseInsensitive) != nil {
            return languageName
        }
        return "\(languageName) (\(String(localized: "Auto-generated")))"
    }
}
