import Foundation

/// One caption language exposed by YouTube's player response.
struct VideoCaptionTrack: Identifiable, Hashable, Sendable {
    let id: String
    let languageCode: String
    let languageName: String
    let url: URL
    let isTranslated: Bool
    let isAutoGenerated: Bool

    var displayName: String {
        if isAutoGenerated {
            return "\(languageName) (auto-generated)"
        }
        if isTranslated {
            return "\(languageName) (translated)"
        }
        return languageName
    }
}
