import Foundation
import Observation

/// Caption selection is local to the current video. Fetching tracks and cues never participates
/// in playback resolution, and changing videos cancels an in-flight cue request.
@available(iOS 17.0, *)
@Observable
@MainActor
final class PlayerCaptionsModel {
    @ObservationIgnored private let videoService: any VideoServicing
    @ObservationIgnored private var cueTask: Task<Void, Never>?

    private(set) var videoID: String?
    private(set) var tracks: [VideoCaptionTrack] = []
    private(set) var cues: [VideoCaptionCue] = []
    private(set) var selectedTrackID: String?
    private(set) var isLoadingTracks = false
    private(set) var isLoadingCues = false
    private(set) var hasTrackError = false
    private(set) var hasCueError = false
    private(set) var hasLoadedTracks = false

    init(videoService: any VideoServicing = VideoService()) {
        self.videoService = videoService
    }

    func reset(for videoID: String?) {
        guard self.videoID != videoID else { return }
        cueTask?.cancel()
        cueTask = nil
        self.videoID = videoID
        tracks = []
        cues = []
        selectedTrackID = nil
        isLoadingTracks = false
        isLoadingCues = false
        hasTrackError = false
        hasCueError = false
        hasLoadedTracks = false
    }

    func loadTracks(for videoID: String, preferredTracks: [VideoCaptionTrack] = []) async {
        guard self.videoID == videoID else { return }
        if !preferredTracks.isEmpty {
            guard tracks != preferredTracks else { return }
            let previousSelection = tracks.first { $0.id == selectedTrackID }
            let replacement = previousSelection.flatMap { selected in
                preferredTracks.first {
                    $0.languageCode == selected.languageCode
                        && $0.isAutoGenerated == selected.isAutoGenerated
                }
            }
            cueTask?.cancel()
            cueTask = nil
            tracks = preferredTracks
            cues = []
            selectedTrackID = nil
            hasLoadedTracks = true
            isLoadingTracks = false
            hasTrackError = false
            hasCueError = false
            if let replacement { select(replacement) }
            return
        }
        guard !hasLoadedTracks, !isLoadingTracks else { return }
        isLoadingTracks = true
        hasTrackError = false
        defer {
            if self.videoID == videoID { isLoadingTracks = false }
        }
        let offlineTracks = await OfflineCaptionStore.shared.tracks(for: videoID)
        guard !Task.isCancelled, self.videoID == videoID, !hasLoadedTracks else { return }
        if !offlineTracks.isEmpty {
            tracks = offlineTracks
            hasLoadedTracks = true
            return
        }
        do {
            let info = try await videoService.fetchInfo(id: videoID)
            guard !Task.isCancelled, self.videoID == videoID, !hasLoadedTracks else { return }
            tracks = info.captionTracks
            hasLoadedTracks = true
        } catch {
            guard !Task.isCancelled, self.videoID == videoID, !hasLoadedTracks else { return }
            hasTrackError = true
        }
    }

    func retryTracks() {
        guard let videoID else { return }
        Task { await loadTracks(for: videoID) }
    }

    func select(_ track: VideoCaptionTrack?) {
        cueTask?.cancel()
        cueTask = nil
        selectedTrackID = track?.id
        cues = []
        hasCueError = false
        isLoadingCues = false
        guard let track, videoID != nil else { return }

        isLoadingCues = true
        cueTask = Task { [weak self] in
            guard let self else { return }
            do {
                let loaded = try await videoService.fetchCaptionCues(track: track)
                guard !Task.isCancelled, selectedTrackID == track.id else { return }
                cues = loaded
            } catch {
                guard !Task.isCancelled, selectedTrackID == track.id else { return }
                hasCueError = true
            }
            if selectedTrackID == track.id { isLoadingCues = false }
        }
    }

    func retrySelectedTrack() {
        guard let track = tracks.first(where: { $0.id == selectedTrackID }) else { return }
        select(track)
    }
}
