import Foundation
import OSLog

import FreeTubeStreamKit

/// Text-only caption sidecars in Documents/Captions, associated with downloaded media by video ID.
/// Signed YouTube URLs are never written to disk. Each native track is separately selectable.
actor OfflineCaptionStore {
    static let shared = OfflineCaptionStore()

    private nonisolated struct Sidecar: Codable {
        let languageCode: String
        let languageName: String
        let isAutoGenerated: Bool
        let cues: [VideoCaptionCue]
    }

    private let log = AppLog(subsystem: "com.leshko.freetube", category: "OfflineCaptions")
    private var activeDownloads = Set<String>()

    private var directory: URL {
        AppDirectories.documents.appendingPathComponent("Captions", isDirectory: true)
    }

    func tracks(for videoID: String) -> [VideoCaptionTrack] {
        guard Self.isSafe(videoID), mediaExists(for: videoID) else { return [] }
        let urls = sidecarURLs(for: videoID)
        return urls.compactMap { url in
            guard let data = try? Data(contentsOf: url),
                  let sidecar = try? JSONDecoder().decode(Sidecar.self, from: data) else { return nil }
            return VideoCaptionTrack(
                id: url.lastPathComponent,
                languageCode: sidecar.languageCode,
                languageName: sidecar.languageName,
                url: url,
                isAutoGenerated: sidecar.isAutoGenerated
            )
        }
    }

    func cues(at url: URL) throws -> [VideoCaptionCue] {
        guard url.isFileURL,
              url.deletingLastPathComponent().standardizedFileURL == directory.standardizedFileURL,
              url.lastPathComponent.hasSuffix(".captions.json") else {
            throw CocoaError(.fileReadNoPermission)
        }
        return try JSONDecoder().decode(Sidecar.self, from: Data(contentsOf: url)).cues
    }

    /// Best effort: caption service failure never changes the media download result.
    func downloadAvailableTracks(for videoID: String) async {
        guard Self.isSafe(videoID), mediaExists(for: videoID),
              activeDownloads.insert(videoID).inserted else { return }
        defer { activeDownloads.remove(videoID) }

        do {
            let source = YouTube(videoID: videoID, methods: [.local])
            let nativeTracks = try await source.captionTracks
            log.info("Found \(nativeTracks.count, privacy: .public) native caption tracks for downloaded \(videoID, privacy: .public)")
            let service = VideoService()
            try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
            for (index, native) in nativeTracks.enumerated() {
                guard !Task.isCancelled, mediaExists(for: videoID) else { break }
                let track = VideoCaptionTrack(
                    id: native.identifier,
                    languageCode: native.languageCode,
                    languageName: native.languageName,
                    url: native.url,
                    isAutoGenerated: native.isAutoGenerated
                )
                let code = Self.safeComponent(track.languageCode)
                let filename = "\(videoID).\(code).\(track.isAutoGenerated ? "auto" : "manual").\(index).captions.json"
                let destination = directory.appendingPathComponent(filename)
                if FileManager.default.fileExists(atPath: destination.path) { continue }
                do {
                    let cues = try await service.fetchCaptionCues(track: track)
                    guard !Task.isCancelled, mediaExists(for: videoID) else { break }
                    guard !cues.isEmpty else { continue }
                    let sidecar = Sidecar(
                        languageCode: track.languageCode,
                        languageName: track.languageName,
                        isAutoGenerated: track.isAutoGenerated,
                        cues: cues
                    )
                    try JSONEncoder().encode(sidecar).write(to: destination, options: .atomic)
                    log.info("Saved offline captions \(filename, privacy: .public) cues=\(cues.count, privacy: .public)")
                } catch {
                    log.notice("Could not save \(track.languageCode, privacy: .public) captions for \(videoID, privacy: .public): \(String(describing: error), privacy: .public)")
                }
            }
        } catch {
            log.notice("Native caption discovery failed for \(videoID, privacy: .public): \(String(describing: error), privacy: .public)")
        }
    }

    func delete(for videoID: String) {
        guard Self.isSafe(videoID) else { return }
        for url in sidecarURLs(for: videoID) {
            try? FileManager.default.removeItem(at: url)
        }
    }

    private func sidecarURLs(for videoID: String) -> [URL] {
        let urls = (try? FileManager.default.contentsOfDirectory(
            at: directory, includingPropertiesForKeys: nil
        )) ?? []
        return urls.filter {
            $0.lastPathComponent.hasPrefix("\(videoID).")
                && $0.lastPathComponent.hasSuffix(".captions.json")
        }.sorted { $0.lastPathComponent < $1.lastPathComponent }
    }

    private func mediaExists(for videoID: String) -> Bool {
        FileManager.default.fileExists(
            atPath: AppDirectories.documents.appendingPathComponent("\(videoID).mp4").path
        )
    }

    private static func isSafe(_ value: String) -> Bool {
        !value.isEmpty && value.unicodeScalars.allSatisfy {
            CharacterSet.alphanumerics.union(CharacterSet(charactersIn: "-_")).contains($0)
        }
    }

    private static func safeComponent(_ value: String) -> String {
        let allowed = CharacterSet.alphanumerics.union(CharacterSet(charactersIn: "-_"))
        let filtered = value.unicodeScalars.filter { allowed.contains($0) }
        return filtered.isEmpty ? "und" : filtered.prefix(32).map { String($0) }.joined()
    }
}
